### ISSUE TITLE
MacOS boots to black screen if external monitor plugged in

### ISSUE THREAD

**Issue by craigbeat** [olm3ca/PixelbookOSX#11]
When booting, the verbose text output will display on both internal and external displays, but when MacOS gets to the login, both screens go black. If I type my password, I can hear my external drive make the noises as if it is actually doing the login, but I cannot do anything to get the display to appear.

**Comment by craigbeat** [comment]
I've been playing about with this a bit - I've installed 'Display Menu' from the App Store, and I've noticed that my external monitor does not work when set to its native resolution. If I set it to 1080p, it will show up and work. Please note that, as per another issue I've raised, I have to let my computer sleep before it will even show up in the menu at all.

If I set my external monitor to 1080p and restart my computer, the external monitor is **_not_** blank when starting up with it plugged in, but the internal monitor is. As was the case before, all the verbose output on the way to the login screen is visible on both. Also, the internal monitor is shown in Display Preferences and the 'Display Menu' app. I've tried adjusting the brightness, but it does not make a difference.

**Comment by olm3ca** [comment]
I think the problem lies in the SSDT-PNLF that we are using. In [this part of the opencore](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#acpi) guide it suggests that if brightness isn't working, you should create a PNLF manually. However, in my attempt at this, there was no patching needed - the prebuilt PNLF already had the correct values. I got stuck here - maybe with your fresh eyes you might notice something if you create your own?

**Comment by olm3ca** [comment]
Also - great find with Display Menu and 1080p resolution. That is at least some progress...
