### ISSUE TITLE
Instructions for dualbooting

### ISSUE THREAD

**Issue by soppelmann** [olm3ca/PixelbookOSX#12]
I can't find any words on how to dualboot with windows even though the screenshot shows it 😀
Is it as simple as to just choose the partition where you want to install as on linux or are any pixelbook specific tricks needed?

I found the Multiboot entry on the OpenCore site here https://dortania.github.io/OpenCore-Multiboot/

**Comment by olm3ca** [comment]
If you have the 128 or 256GB EMMC SSD, you would have Mac OS on an external drive like I did. I had installed Windows 10 on the Pixelbook first, and opencore recognizes it as a boot option automatically.

If you have the 512GB drive, yes you would need to partition the drive for Windows and Mac OS. Since I haven't done that, I'm not able to provide much further guidance.

**Comment by Tpow99** [comment]
I was working on a dual boot from the same drive, I just did a second raw partition and windows was able to format over it

**Comment by olm3ca** [comment]
Great - if there are any steps to get this working that you want to contribute to the repo, feel free to let me know once you have it all working.
