### ISSUE TITLE
That's great. Can you provide the EFI file? thank you very much

### ISSUE THREAD

**Issue by 2697a** [olm3ca/PixelbookOSX#18]
That's great. Can you provide the EFI file? thank you very much

**Comment by meghan06** [comment]
Sharing EFI's is not recommended because troubleshooting it will be a nightmare. If you make the EFI yourself, you know what you changed and what you didn't. That's not the case if you download a prebuilt EFI.

**Comment by 2697a** [comment]
[EFI-Release.zip](https://github.com/olm3ca/PixelbookOSX/files/10799550/EFI-Release.zip)
OK, can you help me see what's wrong with my EFI? It can't be guided

**Comment by meghan06** [comment]
@olm3ca

**Comment by meghan06** [comment]
We do not offer support for premade EFIs / config.plists'. The config.plist you provided is premade per the comments on top, and can even cause your Apple ID to become blacklisted due to invalid SMBIOS data. 

Like I said earlier, premade EFI's are not supported because they are a nightmare to troubleshoot. You don't know what changes the original author has made. Take this for an example: imagine helping somebody that has no idea what he's doing or what changes he made. Not ideal, isn't it?  

Please take the time to go through the Dortania guide and setup your EFI folder yourself. This GitHub repo should be a good starting point. It has all of the information you'll need to get this up and going for your Pixelbook. 

I wish you the best of luck.
[Dortania Guide](https://dortania.github.io/OpenCore-Install-Guide)

**Comment by meghan06** [comment]
There was also a number of errors in your Kext, ACPI, and Drivers folder that would've prevented you from booting altogether.

**Comment by olm3ca** [comment]
Thank you @meghan06 and fully agreed, the only way to get MacOS working on a Pixelbook is to learn the process and to follow the guide. No prebuilt EFIs will be provided. Closing this.
